sudo: required
language: cpp
compiler:
  - gcc
os:
  - linux
before_script:
  - chmod u+x *
script:
  - export GCC_REPO=$(pwd)
  - $GCC_REPO/contrib/download_prerequisites
  - cd ..
  - mkdir objdir
  - cd objdir
  - $GCC_REPO/configure --prefix=$HOME/gcc --enable-languages=c,c++,fortran,go
  - make
  - make install
branches:
  only:
    - master
