sudo: required
language: cpp
compiler:
  - gcc
os:
  - linux
before_script:
  - chmod u+x *
script:
  - export GCC_REPO=$(pwd)
    echo $GCC_REPO
    echo $(pwd)
    cd ..
    echo $(pwd)
    cd ..
    echo $(pwd)
  - exit 1
branches:
  only:
    - master
